/**
 * Writes the generated parts of the markdown that ships in each package:
 *
 * - the rules table in every `packages/*\/README.md`, between
 *   `<!-- begin generated rules -->` and `<!-- end generated rules -->`;
 * - the one-line status header in every `packages/*\/docs/rules/*.md`, right
 *   after the title and the blockquote summary, between
 *   `<!-- begin generated rule header -->` and `<!-- end generated rule header -->`.
 *
 * Both come from the same inventory the site renders from, so a README row, a
 * doc header and a site page cannot disagree about what a rule is. Everything
 * outside the markers is left alone. `readmes.test.ts` regenerates both in
 * memory and fails when a file on disk differs, so a changed `meta` without a
 * rerun fails `bun run test`.
 *
 * Run it with `bun run docs:readmes` at the repo root.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

import {
  REPO_ROOT,
  listRuleDocs,
  loadInventory,
  ruleUrl,
  type PackageEntry,
  type RuleEntry,
} from './inventory';

export const RULES_BEGIN = '<!-- begin generated rules -->';
export const RULES_END = '<!-- end generated rules -->';
export const HEADER_BEGIN = '<!-- begin generated rule header -->';
export const HEADER_END = '<!-- end generated rule header -->';

const NOTE = '<!-- Generated by `bun run docs:readmes` from each rule\'s meta. Do not edit by hand. -->';

export const LEGEND =
  '✅ in `recommended` (error) · ⚙️ needs options · 🔧 `--fix` · 💡 suggestions · 💭 needs type info · ❌ deprecated';

/**
 * A table cell: one line, no unescaped pipe, and no bare `<scope>` outside a
 * code span, which GitHub and npm would swallow as an HTML tag.
 */
function cell(text: string): string {
  return text
    .replace(/\s+/g, ' ')
    .trim()
    .split(/(`[^`]*`)/)
    .map((part, i) => (i % 2 === 1 ? part : part.replace(/</g, '&lt;').replace(/>/g, '&gt;')))
    .join('')
    .replace(/\|/g, '\\|');
}

function linkOf(pkg: PackageEntry, rule: RuleEntry): string {
  return rule.docsUrl ?? ruleUrl(pkg.short, rule.name);
}

/** A replacement rule id as a markdown link to its site page, or a code span when it is not ours. */
export type ReplacementLink = (id: string) => string;

/** Link a `noctcore-<short>/<rule>` id to its page on the site. */
export const siteReplacementLink: ReplacementLink = (id) => {
  const match = /^noctcore-([^/]+)\/(.+)$/.exec(id);
  return match ? `[\`${id}\`](${ruleUrl(match[1]!, match[2]!)})` : `\`${id}\``;
};

function joinLinks(rule: RuleEntry, link: ReplacementLink): string {
  const links = rule.replacedBy.map(link);
  return links.length > 1 ? `${links.slice(0, -1).join(', ')} or ${links.at(-1)}` : (links[0] ?? '');
}

/**
 * The one sentence every surface uses for a deprecated rule:
 * `❌ Deprecated since 1.2.0: <message>. Use <replacement> instead.` The version,
 * message and replacement each drop out when `meta` does not give them.
 */
export function deprecationSentence(rule: RuleEntry, link: ReplacementLink = siteReplacementLink): string {
  const since = rule.deprecatedSince ? ` since ${rule.deprecatedSince}` : '';
  const message = rule.deprecationMessage ? `: ${rule.deprecationMessage.replace(/\.$/, '')}` : '';
  const use = rule.replacedBy.length > 0 ? ` Use ${joinLinks(rule, link)} instead.` : '';
  return `❌ Deprecated${since}${message}.${use}`;
}

function pluginTable(pkg: PackageEntry): string[] {
  const rows = pkg.rules.map((rule) => {
    const name = `${rule.deprecated ? '❌ ' : ''}[\`${rule.name}\`](${linkOf(pkg, rule)})`;
    const replaced =
      rule.deprecated && rule.replacedBy.length > 0 ? ` Replaced by ${joinLinks(rule, siteReplacementLink)}.` : '';
    return [
      name,
      cell(rule.description) + replaced,
      rule.recommended === 'error' ? '✅' : '',
      rule.requiresOptions ? '⚙️' : '',
      rule.fixable ? '🔧' : '',
      rule.hasSuggestions ? '💡' : '',
      rule.typeInfo === 'required' ? '💭' : '',
    ];
  });
  return [
    LEGEND,
    '',
    '| Rule | Description | ✅ | ⚙️ | 🔧 | 💡 | 💭 |',
    '| --- | --- | :-: | :-: | :-: | :-: | :-: |',
    ...rows.map((row) => `| ${row.join(' | ')} |`),
  ];
}

function lintMetaTable(pkg: PackageEntry): string[] {
  // Main entry first, then each sub-entry point, so a reader sees what
  // `createAllRules()` gives before what needs an extra import.
  const rules = [...pkg.rules].sort(
    (a, b) =>
      Number(a.entry !== pkg.npmName) - Number(b.entry !== pkg.npmName) ||
      a.entry!.localeCompare(b.entry!) ||
      a.name.localeCompare(b.name),
  );
  const rows = rules.map((rule) => [
    `[\`${rule.name}\`](${linkOf(pkg, rule)})`,
    cell(rule.description),
    `\`${rule.factory}\``,
    `\`${rule.entry}\``,
    `\`${rule.category}\``,
    rule.ciCritical ? 'yes' : 'no',
  ]);
  return [
    '| Rule | Description | Factory | Import from | Category | Fails CI by default |',
    '| --- | --- | --- | --- | --- | --- |',
    ...rows.map((row) => `| ${row.join(' | ')} |`),
  ];
}

/** The block that sits between the README markers, markers included. */
export function renderRulesBlock(pkg: PackageEntry): string {
  const table = pkg.kind === 'lint-meta' ? lintMetaTable(pkg) : pluginTable(pkg);
  return [RULES_BEGIN, NOTE, '', ...table, RULES_END].join('\n');
}

/** Replace the generated rules block in a README. Throws when the markers are missing. */
export function applyRulesBlock(readme: string, pkg: PackageEntry, path: string): string {
  const start = readme.indexOf(RULES_BEGIN);
  const end = readme.indexOf(RULES_END);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(`${path}: needs a "${RULES_BEGIN}" ... "${RULES_END}" pair where the rules table goes`);
  }
  return readme.slice(0, start) + renderRulesBlock(pkg) + readme.slice(end + RULES_END.length);
}

/**
 * The status line of a rule doc, without its markers. A deprecated rule gets
 * its deprecation sentence as a paragraph of its own above that line.
 */
export function renderRuleHeader(pkg: PackageEntry, rule: RuleEntry): string {
  if (pkg.kind === 'lint-meta') {
    return [
      'Runs under `@noctcore/harness`, not ESLint',
      `Factory \`${rule.factory}\` from \`${rule.entry}\``,
      `Category \`${rule.category}\``,
      `Fails CI by default: ${rule.ciCritical ? 'yes' : 'no'}`,
    ].join(' · ');
  }
  const parts: string[] = [];
  if (rule.recommended === 'error') {
    parts.push('✅ In `recommended` at `error`');
    if (rule.requiresOptions) parts.push('⚙️ Does nothing until configured: needs options (see Options)');
  } else {
    const where = rule.recommended === 'off' ? '`off` in `recommended`' : 'not in `recommended`';
    parts.push(rule.requiresOptions ? `⚙️ Opt-in: ${where}; needs options (see Options)` : `Opt-in: ${where}`);
  }
  if (rule.fixable) parts.push('🔧 Fixable with `--fix`');
  if (rule.hasSuggestions) parts.push('💡 Offers editor suggestions');
  const typeInfo = { required: 'required', optional: 'used when available', none: 'not needed' };
  parts.push(`💭 Type information: ${typeInfo[rule.typeInfo]}`);
  const status = parts.join(' · ');
  return rule.deprecated ? `${deprecationSentence(rule)}\n\n${status}` : status;
}

/** Remove a generated header block, and the blank line after it, from a rule doc. */
export function stripRuleHeader(source: string): string {
  return source.replace(
    new RegExp(`${escapeRegExp(HEADER_BEGIN)}\\n[\\s\\S]*?${escapeRegExp(HEADER_END)}\\n(\\n)?`),
    '',
  );
}

function escapeRegExp(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** Put the generated header right after the title and blockquote summary. */
export function applyRuleHeader(source: string, pkg: PackageEntry, rule: RuleEntry, path: string): string {
  const lines = stripRuleHeader(source.replace(/\r\n/g, '\n')).split('\n');
  if (!/^# `[^`]+`\s*$/.test(lines[0] ?? '')) throw new Error(`${path}: first line must be "# \`<rule id>\`"`);
  let i = 1;
  while (i < lines.length && lines[i]!.trim() === '') i++;
  const quoteStart = i;
  while (i < lines.length && lines[i]!.startsWith('>')) i++;
  if (i === quoteStart) throw new Error(`${path}: expected a "> summary" blockquote after the title`);
  let rest = i;
  while (rest < lines.length && lines[rest]!.trim() === '') rest++;
  return [
    ...lines.slice(0, i),
    '',
    HEADER_BEGIN,
    renderRuleHeader(pkg, rule),
    HEADER_END,
    '',
    ...lines.slice(rest),
  ].join('\n');
}

export interface GeneratedFile {
  readonly path: string;
  readonly current: string;
  readonly expected: string;
}

/** Every README and rule doc as it is on disk and as the generator would write it. */
export async function generate(): Promise<GeneratedFile[]> {
  // Source, not dist: the check in readmes.test.ts must see a meta change
  // before anything is built, and writing from the same source keeps the two in step.
  const inventory = await loadInventory('src');
  const files: GeneratedFile[] = [];
  for (const pkg of inventory) {
    const path = join(pkg.dir, 'README.md');
    const current = readFileSync(path, 'utf8');
    files.push({ path, current, expected: applyRulesBlock(current, pkg, path) });
  }
  const byKey = new Map(
    inventory.flatMap((pkg) => pkg.rules.map((rule) => [`${pkg.short}/${rule.name}`, { pkg, rule }] as const)),
  );
  for (const doc of listRuleDocs()) {
    const owner = byKey.get(`${doc.short}/${doc.rule}`);
    // A doc with no rule is the parity guard's failure to report, not this one's.
    if (!owner) continue;
    const current = readFileSync(doc.path, 'utf8');
    files.push({ path: doc.path, current, expected: applyRuleHeader(current, owner.pkg, owner.rule, doc.path) });
  }
  return files;
}

async function main(): Promise<void> {
  const files = await generate();
  const changed = files.filter((file) => file.current !== file.expected);
  for (const file of changed) {
    writeFileSync(file.path, file.expected);
    console.log(`updated ${relative(REPO_ROOT, file.path)}`);
  }
  console.log(`docs:readmes: ${changed.length} of ${files.length} files changed`);
}

if (import.meta.main) await main();
