import { type ParsedPrismaSchema, tenantBearingAccessors } from './prisma-schema';

/**
 * Reconciles a project's hand-maintained tenant registries against its SCHEMA.
 *
 * A multi-tenant Prisma codebase typically holds three lists of "which models
 * are tenant-scoped?", and only one of them is generated by anything:
 *
 *   1. The model map of its tenant-scope client extension: the runtime
 *      boundary. Without RLS, this is the whole boundary.
 *   2. The model option its tenant lint rules are configured with: the static
 *      boundary.
 *   3. The Prisma schema: every model that actually carries the tenant column.
 *
 * Checking 1 against 2 catches a registry edited on one side only. It cannot
 * catch the worse case: a migration adds a new tenant-bearing table and nobody
 * edits either list, so the new table gets no runtime scope and no lint
 * coverage while both hand lists still agree with each other.
 *
 * So this reconciles against 3. A tenant-bearing model must be either isolated
 * by the extension or named in an explicit exemption map with a written reason,
 * which is the only way an omission is a decision rather than an oversight.
 *
 * The registry itself is the CONSUMER's data. This module ships the shape
 * (`TenantRegistry`) and the check, never a project's model names: pass the
 * registry in from the project that owns it.
 */
export interface TenantRegistry {
  /** Delegate accessors the runtime tenant-scope extension isolates. */
  readonly scopedModels: readonly string[];
  /** Delegate accessor -> why that tenant-bearing model is deliberately NOT isolated. */
  readonly unscopedByDesign: Readonly<Record<string, string>>;
  /**
   * The enforcement half of `unscopedByDesign`: delegate accessor -> the scope
   * fields a query on it must filter by, ANY ONE of which counts. "Scoped by
   * hand" is otherwise a sentence in a comment that nothing checks.
   */
  readonly handScopedModels?: Readonly<Record<string, readonly string[]>>;
  /**
   * Unscoped-by-design models with no `handScopedModels` entry yet, with what
   * it would take to add one, so the next exempted model cannot skip the static
   * guard by simply not being mentioned.
   */
  readonly handScopePending?: Readonly<Record<string, string>>;
}

export interface TenantRegistryReconciliation {
  /** Delegate accessors the schema says carry every tenant field. */
  readonly schemaModels: readonly string[];
  /**
   * Human-readable problems, empty when the registries and schema agree. One
   * message per model so a caller can emit them as separate violations.
   */
  readonly messages: readonly string[];
}

export interface TenantRegistryInput {
  /** Parsed Prisma schema: the source of truth. */
  readonly parsed: ParsedPrismaSchema;
  /** Columns a model must carry to count as tenant-bearing (normally `tenantId`). */
  readonly tenantFields: readonly string[];
  /** Delegate accessors the runtime extension isolates. */
  readonly scopedModels: readonly string[];
  /** Delegate accessor -> why that tenant-bearing model is deliberately unscoped. */
  readonly unscopedByDesign: Readonly<Record<string, string>>;
}

export function reconcileTenantRegistry({
  parsed,
  tenantFields,
  scopedModels,
  unscopedByDesign,
}: TenantRegistryInput): TenantRegistryReconciliation {
  const schemaModels = tenantBearingAccessors(parsed, tenantFields);
  const schemaSet = new Set(schemaModels);
  const scopedSet = new Set(scopedModels);
  const messages: string[] = [];

  const fields = tenantFields.join(' + ');

  for (const model of schemaModels) {
    const exemption = unscopedByDesign[model];

    if (scopedSet.has(model) && exemption !== undefined) {
      messages.push(
        `\`${model}\` is BOTH isolated by the tenant-scope extension and listed as unscoped by design. One of the two is wrong; the extension is the boundary, so drop the exemption unless the model is genuinely leaving it.`,
      );
      continue;
    }

    if (!scopedSet.has(model) && exemption === undefined) {
      messages.push(
        `\`${model}\` carries ${fields} in the Prisma schema but is neither isolated by the tenant-scope extension nor exempt. Unless row-level security covers it, it has no tenant boundary at all. Add it to the extension, or add an unscoped-by-design entry saying how it is scoped instead.`,
      );
    }
  }

  for (const model of Object.keys(unscopedByDesign)) {
    if (!schemaSet.has(model)) {
      messages.push(
        `\`${model}\` is listed as unscoped by design but no schema model with ${fields} maps to that accessor. The exemption is stale: delete it, or fix the accessor name.`,
      );
    }
  }

  for (const model of scopedModels) {
    if (!schemaSet.has(model)) {
      messages.push(
        `\`${model}\` is isolated by the tenant-scope extension but no schema model with ${fields} maps to that accessor, so the scope filter can never match. Either the model lost its ${fields} column or the accessor is misspelled.`,
      );
    }
  }

  return { schemaModels, messages };
}
