import { commentText, looksLikeJsDoc } from '../utils/comments';
import { createRule } from '../createRule';

const RULE_NAME = 'no-narration-comments';

type MessageIds = 'narrationComment';

/*
 * Anchored on the first-person-plural "we" tell of step-by-step narration
 * ("Now we...", "First we..."). Deliberately NOT matching a bare leading word
 * like "First run..." or "Next attempt..." which are legitimate technical
 * comments, only the narration construction.
 */
const NARRATION_PATTERNS: readonly RegExp[] = [
  /^here\s+we\b/iu,
  /^now\s+we\b/iu,
  /^first[,]?\s+we\b/iu,
  /^then[,]?\s+we\b/iu,
  /^next[,]?\s+we\b/iu,
  /^finally[,]?\s+we\b/iu,
  /^let's\b/iu,
  /^let\s+me\b/iu,
];

export const noNarrationCommentsRule = createRule<[], MessageIds>({
  name: RULE_NAME,
  meta: {
    type: 'suggestion',
    docs: {
      description:
        "Disallow narrative comments like 'Here we...', 'Now we...', 'First, we...'. These read as step-by-step prose and add no information a future reader cannot get from the code itself. Often a tell that the comment was generated by an agent describing its own changes.",
    },
    schema: [],
    messages: {
      narrationComment:
        'Narrative comment ({{snippet}}). Describe the WHY, not the sequence of operations, or delete the comment.',
    },
  },
  defaultOptions: [],
  create(context) {
    return {
      Program(): void {
        for (const comment of context.sourceCode.getAllComments()) {
          if (looksLikeJsDoc(comment)) {
            continue;
          }
          const text = commentText(comment);
          if (text === '') {
            continue;
          }
          for (const pattern of NARRATION_PATTERNS) {
            if (pattern.test(text)) {
              const snippet = text.length > 40 ? `${text.slice(0, 40)}...` : text;
              context.report({
                loc: comment.loc,
                messageId: 'narrationComment',
                data: { snippet },
              });
              break;
            }
          }
        }
      },
    };
  },
});
